# Generated by Django 5.0 on 2023-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
